# Copyright 2022 Protosaurus Authors
# Licensed under the Apache License, Version 2.0 (the "License")

name: commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows triggering the workflow manually in github actions page.
  workflow_dispatch:

defaults:
  run:  # use bash for all operating systems unless overridden
    shell: bash

jobs:
  gen:
    name: "gen" # TODO(dio): We should do check instead.
    runs-on: ubuntu-20.04
    timeout-minutes: 90  # instead of 360 by default.
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - uses: actions/cache@v2
        with:
          path: ./.cache/tools
          key: protosaurus-${{ runner.os }}-tools-${{ hashFiles('Tools.mk') }}
      - uses: actions/cache@v2
        with:
          path: ./.cache/buf
          key: protosaurus-${{ runner.os }}-buf-${{ hashFiles('testdata/buf.lock') }}
          restore-keys: protosaurus-${{ runner.os }}-buf-
      - run: make gen
      - run: make docs
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ github.token }}
          publish_dir: website/build
