# Copyright 2022 Protosaurus Authors
# Licensed under the Apache License, Version 2.0 (the "License")

name: commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows triggering the workflow manually in github actions page.
  workflow_dispatch:

defaults:
  run: # use bash for all operating systems unless overridden
    shell: bash

env:
  # This will be added to the docusaurus.baseUrl, i.e. /protosaurus/${BASE_DIR}.
  # Reference: https://docusaurus.io/docs/api/docusaurus-config#baseurl.
  BASE_DIR: "main"

jobs:
  gen:
    name: "gen" # TODO(dio): We should do check instead.
    runs-on: ubuntu-20.04
    timeout-minutes: 90 # instead of 360 by default.
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2

      - name: Fetch current deployed website
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: builds

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - uses: actions/cache@v2
        with:
          path: ./.cache/tools
          key: protosaurus-${{ runner.os }}-tools-${{ hashFiles('Tools.mk') }}
      - uses: actions/cache@v2
        with:
          path: ./.cache/buf
          key: protosaurus-${{ runner.os }}-buf-${{ hashFiles('testdata/buf.lock') }}
          restore-keys: protosaurus-${{ runner.os }}-buf-

      - run: make gen

      # TODO(imballinst): not sure whether to put this test here or to create a new job.
      - run: make test

      - name: Get current PR number
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: jwalton/gh-find-current-pr@v1
        id: current-pr

      # The combination of this and the previous step overrides BASE_URL.
      - name: set BASE_DIR on PR
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          echo "BASE_DIR=pr-${{ steps.current-pr.outputs.pr }}" >> $GITHUB_ENV

      - run: make docs

      - name: Merge all sites
        run: |
          rm -fr builds/${BASE_DIR}
          cp -r website/build builds/${BASE_DIR}
          cp -f index.html builds/index.html

      - name: Publish all sites
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: builds/
          # This allows you to make your publish branch with only the latest commit.
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan.
          force_orphan: true

      - name: Send message to the PR submitter
        uses: actions/github-script@v5
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 you can check the preview on: https://imballinst.github.io/protosaurus/${{ steps.current-pr.outputs.pr }}/.'
            })
